#!/bin/bash
#PBS -N database_build_ABhydro
#PBS -l walltime=24:00:00
#PBS -l select=1:ncpus=24:mem=64GB:ngpus=1
#PBS -e database_build.err
#PBS -o database_build.out
#PBS -M 22042636@sun.ac.za
#PBS -m abe

cd $PBS_O_WORKDIR
source ../tmvec/bin/activate

tmvec-build-database \
    --input-fasta /home/22042636/Masters/2025/TMVec_DeepBLAST/SCOPe/fasta/AB_hydrolases.fasta \
    --tm-vec-model /home/22042636/Masters/2025/TMVec_DeepBLAST/models/tm_vec_swiss_model_large.ckpt \
    --tm-vec-config-path /home/22042636/Masters/2025/TMVec_DeepBLAST/models/49181524_tm_vec_swiss_model_large_params.json \
    --device 'gpu' \
    --output /home/22042636/Masters/2025/TMVec_DeepBLAST/Databases/AB_hydrolases
